### ISSUE TITLE
Light Arrow hint came up as "Undefined"

### ISSUE THREAD

**Issue by MSRB-ARogers** [scatter-dev/zootr-sim#10]
In a tokensanity seed, my Light Arrows were on the "GS Zora River Tree" check, but the hint given by ganon came up with the location as "Undefined"

Spoiler log of the seed: https://pastebin.com/zW5Tc3qB

**Comment by scatter-dev** [comment]
Fixed, it wasn't expecting a skulltula location for light arrows. Thanks!
