### ISSUE TITLE
This repo doesnt seem to have the latest version of the code?

### ISSUE THREAD

**Issue by Zazcallabah** [scatter-dev/zootr-sim#11]
Is it possible to get this updated? :)

**Comment by scatter-dev** [comment]
Yeah, the issue is since I moved to hosting my site on the MEAN stack the code is strewn across a bunch of directories with everything else on the site. Been trying to figure out the best way to do it. I'll probably just make the whole site open source and use that instead of this one.

**Comment by scatter-dev** [comment]
Well, I actually ended up doing this today. Thanks for the inspiration!
