### ISSUE TITLE
Starting items not lit

### ISSUE THREAD

**Issue by Zannick** [scatter-dev/zootr-sim#2]
Items such as the initial wallet, the deku equipment (if enabled), and the Kokiri sword (if not shuffled in) are not lit up in the tracker's initial state. (Alternately, if the sword is not being shuffled in, there should be an action to open that chest.)

Using Chrome 72.

**Comment by scatter-dev** [comment]
I fixed the wallet and deku equipment. I'm going to leave kokiri sword the way it is, since when you actually play the game, you still have to make a point to open the kokiri sword chest, so I think the sim should make you get it too.
