### ISSUE TITLE
Undo function doesn't undo location changes

### ISSUE THREAD

**Issue by Zannick** [scatter-dev/zootr-sim#3]
Means you can end up in a weird state that you have to fix by savewarping, backtracking, or restarting.

**Comment by scatter-dev** [comment]
This is mostly done now. It doesn't work with bosses, but that takes a lot of hardcoding edge cases that I can't be bothered to do at 3 AM. I'll finish it soon. Either way it's about time better undo functionality was in, I knew it had to be improved, I was just too lazy to do it.

**Comment by scatter-dev** [comment]
This is totally done now. Undo should undo everything. The final route doesn't reflect this yet but I'll open a separate issue for that since I need to rewrite how the route works from the ground up to fix it.
