### ISSUE TITLE
Shadow Temple gossip stone misplaced

### ISSUE THREAD

**Issue by sluggusluss** [scatter-dev/zootr-sim#4]
Small comment but the Shadow Temple gossip stone should be in Above Graveyard rather than Graveyard.

Keep up the great work!

**Comment by scatter-dev** [comment]
I went back and forth for a while on whether Above Graveyard should be its own region or not. I'm still not sure if that's the best way to do it, but as long as it exists, the stone should be in the right place. Fixed, thanks for reporting!
