### ISSUE TITLE
Missing Light Trial Chest

### ISSUE THREAD

**Issue by exodus122** [scatter-dev/zootr-sim#5]
"Ganons Castle Light Trial Invisible Enemies Chest" is missing from the simulator

**Comment by scatter-dev** [comment]
That used to be misspelled as "Trail". I figured it'd be fixed at some point, which of course I didn't bother future proofing against. Not sure whether it was hotfixed in v4.0 or if I just missed it when I upgraded a few months ago. Either way, fixed.
