### ISSUE TITLE
Allow checking of "Colossus Freestanding PoH" as child

### ISSUE THREAD

**Issue by exodus122** [scatter-dev/zootr-sim#6]
This can be seen as child, so we should be allowed to check it as child to see what it is. Currently, the simulator makes you go adult just to check it then go back to child to continue the playthrough.

This could also be changed for the "DM Crater Volcano Freestanding PoH"

**Comment by scatter-dev** [comment]
This is something that will be fixed naturally when I implement viewing of all freestanding items (see #9 ).
